/* eslint-disable */
/**
 * Generated by Convex (stub for local builds).
 * Run `npx convex dev` to regenerate with real types.
 */
import { anyApi } from "convex/server";

export const api: any = anyApi;
export const internal: any = anyApi;
